### ISSUE TITLE
Vertical scale for the graph component

### ISSUE THREAD

**Issue by Armael** [janestreet/memtrace_viewer#6]
I unfortunately couldn't manage to build the code in the released branch, so I've only used the version currently released in opam.

It would be useful to have a vertical scale for the memory consumption graph (in the green panel), similar to the horizontal time scale. Maybe I'm missing something but for instance I couldn't find a way of getting the peak memory consumption and that's something that could be read from the graph.

**Comment by lpw25** [comment]
A vertical scale would be useful. I'll add that to our todo list.

In our more recent versions, you can work out the peak memory consumption by filtering to only those allocations live at the peak and then reading of the "Filtered allocations" that is printed in the filter panel.

I think that if you use our [bleeding edge repo](https://github.com/janestreet/opam-repository) you can build our more recent versions. Unfortunately, they probably won't make it onto main opam until we do a next stable release of all our packages.

**Comment by lpw25** [comment]
This is now fixed and the filter panel also has a bit that tells you what the peak live memory was.
