### ISSUE TITLE
OCaml 4.12

### ISSUE THREAD

**Issue by zbroyar** [janestreet/memtrace_viewer#7]
Hi,

First of all I'd like to thank for the tool :-)

Second, I see that ocaml 4.12 is not supported. Is there any plans to support it in the nearest future?

Thanks for the answer.

**Comment by lpw25** [comment]
4.12 support will be released when the rest of Jane Street's libraries move to 4.12. That's probably still a while away. However, do you actually need the viewer to build with 4.12? Profiles taken with the memtrace library on 4.12 should be viewable by a viewer built with 4.11.

**Comment by zbroyar** [comment]
@lpw25 thanks for the info, I will try to use 4.11 viewer.

**Comment by kit-ty-kate** [comment]
A more practical requirement for OCaml 4.12 (4.13 due in a week, would also be fantastic) is for macOS/arm64 as OCaml 4.11 does not support this platform.

**Comment by toots** [comment]
I'd like to add a +1 on this. `4.11` is become old and I am currently facing a situation where I have to switch back to `4.11` just to run a viewer. This tool is fantastic, please do not let it become obsolete.

**Comment by lpw25** [comment]
v0.15.0 is on opam and works with 4.12 and newer.
