### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by arthaud** [janestreet/memtrace_viewer#9]
Hello,

I'm getting an error when trying to install memtrace_viewer via opam.
I'm running `opam install memtrace_viewer`.
This is on macOS Montery version 12.3, opam 2.1.2 and an opam switch for ocaml 4.11.2.
```
⬇ retrieved memtrace_viewer.v0.14.1  (cached)
[ERROR] The compilation of memtrace_viewer.v0.14.1 failed at "dune build --profile release --default-target @install . --root .".

#=== ERROR while compiling memtrace_viewer.v0.14.1 ============================#
# context     2.1.2 | macos/x86_64 | ocaml-base-compiler.4.11.2 | https://opam.ocaml.org#9d91fc65
# path        ~/.opam/4.11.2/.opam-switch/build/memtrace_viewer.v0.14.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build --profile release --default-target @install . --root .
# exit-code   1
# env-file    ~/.opam/log/memtrace_viewer-18663-2e8d2e.env
# output-file ~/.opam/log/memtrace_viewer-18663-2e8d2e.out
### output ###
# [...]
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "vendor/gen_js_api/ppx-lib/gen_js_api_ppx.ml", line 1368, characters 43-58:
# 1368 |       let class_typ = Typ.constr (mknoloc (Longident.parse class_name)) [] in
#                                                   ^^^^^^^^^^^^^^^
# Alert deprecated: Migrate_parsetree.Ast_408.Longident.parse
# this function may misparse its input,
# use "Parse.longident" or "Longident.unflatten"
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Toploop, and its interface was not compiled with -opaque
```

See logs:
[memtrace_viewer-18663-2e8d2e.env.txt](https://github.com/janestreet/memtrace_viewer/files/8354415/memtrace_viewer-18663-2e8d2e.env.txt)
[memtrace_viewer-18663-2e8d2e.out.txt](https://github.com/janestreet/memtrace_viewer/files/8354416/memtrace_viewer-18663-2e8d2e.out.txt)

**Comment by arthaud** [comment]
Is this supported on macOS? I tried to build from source and got:
```
[ERROR] Package conflict!
  * Missing dependency:
    - ocaml_intrinsics
    unmet availability conditions: '(arch = "x86_32" | arch = "x86_64") & os = "linux"'
```

**Comment by lpw25** [comment]
The failure on macOS seems to be caused by: https://github.com/janestreet/ocaml_intrinsics/issues/4. Not sure how we depend on `ocaml_intrinsics`, but I'd expect that to be fixed soon.

The other issue is from building the previous version, which has all the dependencies vendored in, whose source is here: https://github.com/janestreet/memtrace_viewer_with_deps. It looks like an incompatibility with the latest release of Sexplib0, which probably means that our opam file is missing a dependency. If you force Sexplib0 down to version v0.14.1 then it should work.

**Comment by lpw25** [comment]
https://github.com/ocaml/opam-repository/pull/21114 should hopefully fix the original issue.
